---
  plugins:
    - json

  env:
    node: true
    es6: true

  rules:
    curly:
      - 2
      - "all"
    keyword-spacing:
      - 2
      - {}
    space-before-blocks:
      - 2
      - "always"
    comma-spacing:
      - 2
      -
        before: false
        after: true
    space-before-function-paren:
      - 2
      -
        named: "never"
        anonymous: "always"
        asyncArrow: "ignore"
    padded-blocks:
      - 2
      - "never"
    no-empty:
      - 2
      -
        allowEmptyCatch: true
    no-nested-ternary: 2
    no-unused-vars:
      - 2
    no-undef:
      - 2
    space-in-parens:
      - 2
      - "never"
    quote-props:
      - 2
      - "as-needed"
    semi: 0
    key-spacing:
      - 2
      -
        beforeColon: false
        afterColon: true
    comma-style:
      - 2
      - "last"
    operator-linebreak: 0
    space-unary-ops:
      - 2
      -
        words: false
        nonwords: false
    semi-spacing:
      - 2
      -
        before: false
        after: true
    space-infix-ops: 2
    camelcase:
      - 2
      -
        properties: "always"
    no-with: 2
    no-multi-str: 2
    linebreak-style:
      - 2
      - "unix"
    quotes:
      - 2
      - "single"
      -
        allowTemplateLiterals: true
    indent:
      - 2
      - 2
      -
        SwitchCase: 1
    no-mixed-spaces-and-tabs: 2
    no-trailing-spaces: 2
    comma-dangle: 0
    no-spaced-func: 2
    brace-style:
      - 2
      - "1tbs"
      -
        allowSingleLine: true
    max-len:
      - 2
      - 120
    consistent-this:
      - 2
      - "self"
    dot-notation:
      - 2
      -
        allowPattern: "^[a-z]+(_[a-z]+)+$"
    yoda:
      - 2
      - "never"
    valid-jsdoc: 2
    require-jsdoc:
      - 2
      -
        require:
          FunctionDeclaration: false
          MethodDefinition: true
          ClassDeclaration: true

